apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Cloud Run development service
run:
 location: projects/project-aims-dev/locations/us-central1
executionConfigs:
- defaultPool:
    serviceAccount: aims-dev-ci-cd-sa@project-ci-cd.iam.gserviceaccount.com
  usages:
  - RENDER
  - DEPLOY