apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Cloud Run production service
run:
 location: projects/project-aims-qa/locations/us-central1
executionConfigs:
- defaultPool:
    serviceAccount: aims-qa-ci-cd-sa@project-ci-cd.iam.gserviceaccount.com
  usages:
  - RENDER
  - DEPLOY
